### ISSUE TITLE
チャットの設定で失敗しました

### ISSUE THREAD

**Issue by Shiryo712** [Shiryo712/OfficeWorkManual#2]
マニュアルで解説されているチャットの設定がうまくできませんでした。
掲載されているURLは正しいでしょうか？

**Comment by Zhiliang712** [comment]
確認しましたがURLには問題ないようです。
詳しい症状を教えてもらえますか？

**Comment by Shiryo712** [comment]
すみません、ネットワークケーブルが抜けてました。
